version: '3'

services:
  grav:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${GRAV_IMAGE}:${GRAV_TAG}
    restart: unless-stopped
    hostname: 
    volumes: ${DOMAIN}
      - grav_data:/var/www/html
    environment:
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_LANG: ${ADMIN_LANG}
      ADMIN_FULLNAME: ${ADMIN_FULLNAME}
      ADMIN_TITLE: ${ADMIN_TITLE}
      TIMEZONE: ${TIMEZONE}
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN}

volumes:
  grav_data:

networks:
  default:
    name: ${NETWORK}
    external: true
