version: '3'

services:
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      #POSTGRES_INITDB_ARGS: odoo -i base -d ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped

  odoo:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${ODOO_IMAGE}:${ODOO_TAG}
    restart: unless-stopped
    links:
      - postgres:postgres
#    ports:
#      - "${ODOO_PORT}:8069"
#      - "${CHAT_PORT}:8072" # live chat
#    expose:
#      - "${ODOO_PORT}:8069"
#      - "${CHAT_PORT}:8072" # live chat
    tty: true
    volumes:
      - extra-addons:/mnt/extra-addons
    command: -- --dev=reload
    environment:
      HOST: ${COMPOSE_PROJECT_NAME}-postgres
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      VIRTUAL_PORT: 8069
      VIRTUAL_HOST: ${URL},www.${URL}
      LETSENCRYPT_HOST: ${URL},www.${URL}

volumes:
  postgres-db:
  extra-addons:

networks:
  default:
    name: ${NETWORK}
    external: true
