version: '3'
services:
  wg-easy:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${WIREGUARD_IMAGE}:${WIREGUARD_TAG}
    ports:
      - ${WG_CONFIG_PORT}:51820/udp
      - ${WIREGUARD_UI_PORT}:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - etc_wireguard:/etc/wireguard
    environment:
      LANG: ${LANG}
      WG_HOST: ${WIREGUARD_URL}
      PASSWORD_HASH: ${PASSWORD_HASH} # generate password hash on https://bcrypt.online/
      WG_PORT: ${WG_CONFIG_PORT}
      PORT: ${WIREGUARD_UI_PORT}
      WG_DEFAULT_ADDRESS: ${WG_DEFAULT_ADDRESS}
      WG_DEFAULT_DNS: ${WG_DEFAULT_DNS}
      WG_MTU: ${WG_MTU}
      WG_PERSISTENT_KEEPALIVE: ${WG_PERSISTENT_KEEPALIVE}
      UI_TRAFFIC_STATS: ${UI_TRAFFIC_STATS}
      UI_CHART_TYPE: ${UI_CHART_TYPE}
      VIRTUAL_PORT: ${WIREGUARD_UI_PORT}
      VIRTUAL_HOST: ${WIREGUARD_URL}
      LETSENCRYPT_HOST: ${WIREGUARD_URL}

volumes:
  etc_wireguard:

networks:
  default:
    name: ${NETWORK}
    external: true